name: Docker Publish Develop

on:
  push:
    branches: [ master ]

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          # Pycharm professional
          - imageName: projector-pycharm-p
            tag: 2021.3.1
            downloadLink: https://download.jetbrains.com/python/pycharm-professional-2021.3.1.tar.gz
            isLatest: true

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: projector-docker

      - name: Checkout server repo
        uses: actions/checkout@v2
        with:
          repository: JetBrains/projector-server
          path: projector-server

      - name: Push exact version
        run: |
          cd projector-docker
          ./build-container.sh ${{ matrix.imageName}}:${{ matrix.tag }} ${{ matrix.downloadLink }}
          docker save ${{ matrix.imageName}}:${{ matrix.tag }} | gzip > ${{ matrix.imageName}}-${{ matrix.tag }}-${{ github.run_number }}.tar.gz

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.imageName}}-${{ matrix.tag }}-${{ github.run_number }}
          path: ${{ matrix.imageName}}-${{ matrix.tag }}-${{ github.run_number }}.tar.gz
